package com.cmch.mimascotavirtual.ui.theme

import androidx.compose.ui.graphics.Color

// COLORES PARA EL TEMA CLARO
val LightPrimary = Color(0xFF9442a1)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFFFD6F8)
val LightOnPrimaryContainer = Color(0xFF390045)
val LightSecondary = Color(0xFF6C586B)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFF6DBF5)
val LightOnSecondaryContainer = Color(0xFF261626)
val LightTertiary = Color(0xFF825247)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFDBD2)
val LightOnTertiaryContainer = Color(0xFF33110A)
val LightError = Color(0xFFBA1A1A)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnError = Color(0xFFFFFFFF)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFFFBFF)
val LightOnBackground = Color(0xFF1F1A1D)
val LightSurface = Color(0xFFFFFBFF)
val LightOnSurface = Color(0xFF1F1A1D)
val LightSurfaceVariant = Color(0xFFEDDEE8)
val LightOnSurfaceVariant = Color(0xFF4D444C)
val LightOutline = Color(0xFF7E747C)
val LightInverseOnSurface = Color(0xFFF8EEF2)
val LightInverseSurface = Color(0xFF342F32)
val LightInversePrimary = Color(0xFFFFA9FE)
val LightSurfaceTint = Color(0xFF9442a1)
val LightOutlineVariant = Color(0xFFD0C3CC)
val LightScrim = Color(0xFF000000)

// COLORES PARA EL TEMA OSCURO
val DarkPrimary = Color(0xFFFFA9FE)
val DarkOnPrimary = Color(0xFF5C0E6E)
val DarkPrimaryContainer = Color(0xFF782987)
val DarkOnPrimaryContainer = Color(0xFFFFD6F8)
val DarkSecondary = Color(0xFFD9BFD8)
val DarkOnSecondary = Color(0xFF3C2B3B)
val DarkSecondaryContainer = Color(0xFF544153)
val DarkOnSecondaryContainer = Color(0xFFF6DBF5)
val DarkTertiary = Color(0xFFF6B9A9)
val DarkOnTertiary = Color(0xFF4D251D)
val DarkTertiaryContainer = Color(0xFF683B32)
val DarkOnTertiaryContainer = Color(0xFFFFDBD2)
val DarkError = Color(0xFFFFB4AB)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnError = Color(0xFF690005)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF1F1A1D)
val DarkOnBackground = Color(0xFFE9E0E4)
val DarkSurface = Color(0xFF1F1A1D)
val DarkOnSurface = Color(0xFFE9E0E4)
val DarkSurfaceVariant = Color(0xFF4D444C)
val DarkOnSurfaceVariant = Color(0xFFD0C3CC)
val DarkOutline = Color(0xFF988E96)
val DarkInverseOnSurface = Color(0xFF1F1A1D)
val DarkInverseSurface = Color(0xFFE9E0E4)
val DarkInversePrimary = Color(0xFF9442a1)
val DarkSurfaceTint = Color(0xFFFFA9FE)
val DarkOutlineVariant = Color(0xFF4D444C)
val DarkScrim = Color(0xFF000000)
